### ISSUE TITLE
Acknowledgement of original authors

### ISSUE THREAD

**Issue by kahilah** [Aalto-CFD/ConeCylinderInjection#2]
In readme as well as in the code base, Professor Vuorinen and Wehrfritz (and their corresponding papers) should be mentioned as they can be considered as the original authors.

**Comment by mahgadalla** [comment]
@kahilah Thanks for your note. I have made an explicit statement in the readme description mentioning it is a re-implementation of an earlier in-house version (i.e. not exactly the same, apart from code adaptation), so hopefully this can be sufficient. The src base includes a link to the repo with readme. Prof. Vuorinen and Wehrfritz are acknowledged in Ref.2 already, and after some check I could not find any details from previous papers noting this implementation. I will close the issue for now as completed, but please consider re-opening if you think it is not sufficient.
